# Generated by Django 5.1.6 on 2025-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodels',
            name='ticket',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
